### ISSUE TITLE
Make note accidentals respect a key signature/scale?

### ISSUE THREAD

**Issue by BHSPitMonkey** [saebekassebil/teoria#101]
I'm wondering if Teoria has a way of figuring out the appropriate accidental for a note, with respect to a given key signature (or Scale object, more probably).

More specifically: I would like to be able to create a Bb major `Chord` with a F major `Scale` specified, and find no accidentals on any of the notes in that scale. I was looking around for a way to pass a `Scale` to `teoria.chord(...)`, or maybe find a chord generator as a method of `Scale`, but didn't find anything. Does this functionality currently exist in some form?

**Comment by BHSPitMonkey** [comment]
Actually, I might not have a use case for this anymore; the engraving library I'm using is able to do this. Leaving this issue open for discussion in case anyone has thoughts.

**Comment by saebekassebil** [comment]
Wouldn't it be enough to iterate trough all your notes, checking if they're in the current scale (with `Note.scaleDegree`) and deciding whether to show the accidental based on that?

Cheers, and thanks for reporting!
Jakob

**Comment by BHSPitMonkey** [comment]
I had actually started down that road, but realized it would need to be even smarter in cases where the same note appears more than once in the same measure. Given that Teoria doesn't track that kind of information, it's probably best to leave that behavior to an engraving engine. I'll go ahead and close this until someone comes along and has more to say!
