### ISSUE TITLE
Check if two notes are equal

### ISSUE THREAD

**Issue by amitgur** [saebekassebil/teoria#104]
What is the best way?

I'm doing this.. 

var checkEqualNotes = function(a,b){

  var interval = teoria.interval(teoria.note(a),teoria.note(b)).toString();

  if (interval ==='P1' || interval === 'd-2' || interval === 'd2'){
    return true;
  } else {
    return false;
  }
}

**Comment by saebekassebil** [comment]
Hey Amit,

Equal in which way? Pitch equal or harmonically (theoretically) equal?

Use Nota#key or Note#chroma for pitch equal and maybe just compare Note.coord if they should be harmonically equal?

// Jakob

**Comment by amitgur** [comment]
Pitch equal
a#3 === bb3 this are not equal by key???

**Comment by saebekassebil** [comment]
Yea, they should be equal by key?

**Comment by amitgur** [comment]
:+1: Gotit

**Comment by saebekassebil** [comment]
Closing this as I see no outstanding issue(?)
