### ISSUE TITLE
add more scales

### ISSUE THREAD

**Issue by eagor** [saebekassebil/teoria#109]
the list of KNOWN_SCALES is pretty basic. Would be handy if teoria knew most (if not all) of the scales existing out there. I'm willing to run through Wikipedia and make up a list of scales, and then pull request the changes.

**Comment by saebekassebil** [comment]
Maybe just publish a module with scales that could be required when needed?

**Comment by ianring** [comment]
Perhaps this other project I've been working on could offer some cross-pollination. It includes a pretty good list of scales... the tones in each scale are represented as a binary bitmask.

https://github.com/ianring/PHPMusicTools/blob/master/src/PHPMusicTools/classes/Scale.php

Of course if you want all the scales, there's http://allthescales.org/
