### ISSUE TITLE
Getting chordType "trichord" instead of "triad" and "unknown" instead of "tetrad"

### ISSUE THREAD

**Issue by Scriptim** [saebekassebil/teoria#115]
When I try to get the _chordType_ of a _Chord_ instance, I get following results:

**trichord** for **CM** (should be _triad_)
**unknown** for **C7** (should be _tetrad_)

I have the same problems with similar chords. Is this a bug or my fault?

![teoria](https://user-images.githubusercontent.com/13003924/27256557-18948604-53b9-11e7-8310-c5e59a71729c.png)

**Comment by saebekassebil** [comment]
Hey @Scriptim ! Sorry for getting back so late, but the late exams have been over me and time has been in shortage.

Anyway: Trichord is (to my knowledge) the more general term of any chord consisting of 3 notes. So Tri-chord for Cm is not *per se* wrong. But it would indeed be more correct to say triad. Same goes for C7 (which I thought already worked..)

I'll look into it and come back

**Comment by saebekassebil** [comment]
Hey again - looked into it, and it was a silly mistake in the code barring this from working properly. It should work now, and I've added some tests, but please try it out and let me know if it doesn't!

Thanks for the notice :)

**Comment by Scriptim** [comment]
It works fine for me, thank you very much. Great project
