### ISSUE TITLE
Scientific or frequency number output from scale 

### ISSUE THREAD

**Issue by tatecarson** [saebekassebil/teoria#116]
Hi, 
I'm trying to use teoria to generate scales and chords for Tonejs, which takes either frequency numbers or scientific notation. 

```
 var a4 = teoria.note('A4');
 var scale = a4.scale('mixolydian').simple()
```

This outputs an array of note names, but is there any way to either convert them to the scientific notation or frequency numbers?

**Comment by saebekassebil** [comment]
You could use the array methods (like map) to iterate over the notes, which you can get with the #notes() method on a scale and chord

/j

**Comment by tatecarson** [comment]
Thank you, very helpful.
