### ISSUE TITLE
Create a chord with root different from the tone

### ISSUE THREAD

**Issue by gsouf** [saebekassebil/teoria#59]
Hi,

Not sure about the correct english name of what i want to explain, an exemple worth 10000 words. 

I dont find the way to build such a chord : ``A/B`` : A chord with ``A``  as the tonic and ``B`` as the bass.

Is there a way to do so in the current version ?

**Comment by saebekassebil** [comment]
Fixed per d9a04c94fa39c599b817ec28eb064fbe6545ebe2
