### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by gpascale** [saebekassebil/teoria#60]
Is this project still active?

I've followed the build steps, but "jake build" fails - missing underscore. Tried adding underscore manually to the package.json but then it complains about missing console-browserify.

**Comment by saebekassebil** [comment]
Closing this, as it has nothing to do with teoria. Feel free to write again @gpascale if you want some help.

**Comment by MJKEYS21** [comment]
hey i need some help   i am switching chord detect scripts and i need your help with the coding to make it work

**Comment by saebekassebil** [comment]
Hi MJKEYS21, I'm not quite sure what you mean, but if you feel like you have an issue with the teoria library feel free to open a new issue and I'll try to take a look at it.
