### ISSUE TITLE
Equal Notes

### ISSUE THREAD

**Issue by amitgur** [saebekassebil/teoria#67]
I need to examine if two notes are the same pitch, Gb = F# etc. I wrote this simple fonction. It there another way to do that ? 

teoria.checkEqualNotes = function(a,b){

	var interval = teoria.interval(teoria.note(a),teoria.note(b)).toString();

	if (interval ==='P1' || interval === 'd-2' || interval === 'd2'){
		return true;
	} else {
		return false;
	}
}

**Comment by saebekassebil** [comment]
[TeoriaNote#chroma()](https://github.com/saebekassebil/teoria#teorianotechroma) :)
