### ISSUE TITLE
Reharmonization library for Teoria?

### ISSUE THREAD

**Issue by thomasnordlund** [saebekassebil/teoria#69]
I'd like to create a reharmonization library that depends on teoria. Would you be interested in something like this? I see the library providing methods for calculating reharmonizations using all of the standard techniques and then some. I see that Jason Storey created teoria-chord-progression as a standalone package. I'm thinking that would be a good approach for a library like this as well?

**Comment by saebekassebil** [comment]
Yes yes yes! What a cool application. It's really a shame that you can't "require" just parts of the library as of yet (I'm working on it). But yes - I think it'd be the right way to go, to  create a separate module in npm.

**Comment by saebekassebil** [comment]
PS: Please send me a link to your work - it'd be happy to help out if I find the time

**Comment by thomasnordlund** [comment]
Awesome! I setup a new repo at https://github.com/thomasnordlund/teoria-reharm and added you as a collaborator in the event that you want to help. I'll be starting to work on this soon. Thanks for a great library!

**Comment by saebekassebil** [comment]
Closing issue, as further development continues on https://github.com/thomasnordlund/teoria-reharm
