### ISSUE TITLE
M for major

### ISSUE THREAD

**Issue by pianoboygit** [saebekassebil/teoria#71]
Teoria currently interprets "CM7" as a "C7" (dominant 7th) chord, when it should interpret it as a "Cmaj7".

A capitalized "M" in chord names is synonymous with "Maj". While using "M" is bad practice (due to confusion with lower-case "m", especially with certain fonts), it is universally recognized as meaning "major", and unfortunately this notation is common enough in books, sheet music, and chord charts, that teoria should probably support it.

Note: I know that teoria supports "M" as a standalone 7th qualifier, and it should continue to support this. e.g. don't change the behaviour of "CmM7" (C minor chord with major 7th) or "C+M7" (C augmented chord with major 7th). But in addition to that, "M" should be equivalent to "Maj" when used for the chord quality definitions themselves.  In other words, when "M" immediately follows the note name, it should act the same as if it were "Maj" following the note name. Examples: "CM13" == "Cmaj13", "BbM7#11" == "BbMaj7#11".

Similar to this, I would also recommend allowing "Ma" as another "maj" equivalent, and "Mi" for "min". Example usages: 
* https://www.google.ca/search?q=%22Cmi7%22&espv=2&biw=1920&bih=955&tbm=isch&tbo=u&source=univ&sa=X&ei=v6wVVfiOGNjjoASowYGgBA&ved=0CCcQ7Ak
* https://books.google.ca/books?id=mjaITr2NdkEC&pg=PA208&lpg=PA208&dq=%22Cmi7%22&source=bl&ots=4JXE1DuGqG&sig=OONirDPjltjcRgFAgl_Fh-V2A4o&hl=en&sa=X&ei=O6wVVdPIFpLfoATMkIGADg&ved=0CE8Q6AEwCg#v=onepage&q=%22Cmi7%22&f=false

**Comment by saebekassebil** [comment]
You're right! I thought this already worked. Well. Let me look into that!

Thanks for reporting. We should probably support Ma and Mi as well, and you're welcome to submit a PR for that if you want.

**Comment by pianoboygit** [comment]
Cool. FYI I'm not actually using teoria (but great project!). This all stemmed from this post on /r/piano: http://www.reddit.com/r/piano/comments/30cuyq/i_built_a_web_application_that_visually_shows/

**Comment by saebekassebil** [comment]
@pianoboygit: working as of `v1.5.0`

I've implemented 'Ma' as 'Maj' - and I've always been taught (and from what I've read) that 'Cmaj' = 'Cmaj7'. And so teoria now parses 'Cma7' as 'Cmaj7'. Is that correct in your opinion?

**Comment by saebekassebil** [comment]
Sorry, minor misunderstanding. Status as of `v1.6.0`:

  - CM = C major triad
  - CMa = C major triad
  - CMaj = C major seventh (Cmaj7)
  - CM7 = C major seventh (Cmaj7)
  - Cma7 = C major seventh (Cmaj 7)
  - Cm = C minor triad
  - Cmi = C minor triad
  - Cmin = C minor triad
