### ISSUE TITLE
Export constant objects from core.js

### ISSUE THREAD

**Issue by secrettriangle** [saebekassebil/teoria#72]

**Comment by saebekassebil** [comment]
There's an ongoing effort of modularizing this lib better. See the [modularado branch](https://github.com/saebekassebil/teoria/tree/modularado) and the following modules:

[notecoord](https://github.com/saebekassebil/notecoord) - A data package containing the relative intervals bewteen notes in the Western music system
[accidental-value](https://github.com/saebekassebil/accidental-value) - The relative interval values of accidentals in music
[d'accord](https://github.com/saebekassebil/daccord) - A chord parsing module (independent of teoria)

If there's something specific you require, let me know.

**Comment by saebekassebil** [comment]
@secrettriangle I'm closing these two issues, as you've provided no description of what it is you want in detail. Feel free to open some new ones with more words in them

**Comment by secrettriangle** [comment]
Ask and you shall receive. All of [this](https://github.com/saebekassebil/teoria/blob/master/src/core.js#L32-L193) should be accessible somehow rather than `var`s within a closure.

**Comment by secrettriangle** [comment]
Really quite simple, don't know how much more info there is to provide.

**Comment by secrettriangle** [comment]
Does that make sense? Should I provide more info or open a new ticket?

**Comment by saebekassebil** [comment]
I quite agree that those things should be "accessible" in some way. But I don't believe a quick-fix is what this library needs. Some of those things are already available in the modules I linked you to earlier, some are not. We/I need to fix that, and I think #78 is going to take us closer the goal of exposing this stuff.

I'll reopen this, so we can keep track of what info is available as we progress. You're more than welcome to contribute to this if you have the time.

**Comment by secrettriangle** [comment]
I just mean that we should turn those vars into properties of already-exported objects somehow. That may not be the perfect solution but at least people will have the ability to access the information without having to copy/paste. (I happen to think it's a fine solution but I have only a cursory understanding of teoria.)

**Comment by saebekassebil** [comment]
Done. Ha. This was a very nice side-effect benefit from structuring this library in a more modular (node-compatible) way.

You can get all the "music-theory knowledge" from `teoria~1.8.0` by doing:
```js
var knowledge = require('teoria/lib/knowledge');
```

I know this is a bit "hidden" and it's true that the knowledge is a symptom of something growing too big, but I hope that it'll help you out for now.

Let me know if it works for you!

**Comment by secrettriangle** [comment]
Awesome! Nice work @saebekassebil :smile:

We should also move [the scales](https://github.com/saebekassebil/teoria/blob/master/lib/scale.js#L4) and all other constants into `knowledge.js` or export them somehow.
