### ISSUE TITLE
Build Example Fails with more Scales

### ISSUE THREAD

**Issue by JRJurman** [saebekassebil/teoria#75]
Not sure if this is an issue with my environment or not, I definitely was able to build this when I had cloned it on a different machine, but I get this error when trying to build (this is the example given in the readme).

![image](https://cloud.githubusercontent.com/assets/326557/7386288/f4931442-ee1f-11e4-9f03-e433fa6696d3.png)

Also, is there a way to just say I want ALL the scales? Not sure if there is a shorthand for that or not, but it would be useful...

Regardless, I might just for now add them manually to the jake file if I can, but I figured I would shoot this out.

**Comment by saebekassebil** [comment]
Hey @JRJurman !

Well, actually I'm not to keen on our entire build process - but of course it should work! I'll look into it asap.

Thanks for reporting.

**Comment by saebekassebil** [comment]
Works here (I'm using Bash on Mac OS X). It looks like PowerShell does something to the arguments when you comma-separate stuff on the command line. Maybe try to escape the commas?

**Comment by saebekassebil** [comment]
@JRJurman Try this (taken from [StackOverflow](http://stackoverflow.com/questions/11990688/powershell-is-removing-comma-from-program-argument)

    jake build scales=+blues`,+flamenco`,-chromatic

Apparently the ` "escapes" the comma

**Comment by JRJurman** [comment]
Yep that was the issue!
And just trying it now in cmd, it seems to work just fine with what's in your readme... Thanks for the help!
