### ISSUE TITLE
MusicJSON Support?

### ISSUE THREAD

**Issue by mcory** [saebekassebil/teoria#76]
Hopefully this isn't just because I missed something obvious, but is there any support in teoria for the MusicJSON format (specifically, the output from your musicjson library at https://github.com/saebekassebil/musicjson)? I'm playing around with some analytic stuff, and using the musicjson library to get MusicXML files in something I can work with; teoria seems like it might handle a bit more of the theory-related stuff for what I'm doing, but I'd rather not manually create the teoria objects if there's a parser for your json stuff somewhere. 

Thanks!

**Comment by saebekassebil** [comment]
Hey @mcory! There's no parser as there is no real concept of "time" in teoria right now. So I'm afraid it's "manually" creating the objects.

I'd be very interested in seeing how you'd structure it - where you thinking of something in particular? Like what kind of structure would the parser hand you back, etc?

**Comment by mcory** [comment]
Thanks for the quick response! Honestly, I have absolutely no clue how I'd structure anything at the moment - it was more that I'd work with what the parser gave me (if there was one). I haven't even dug into teoria at all, it just seemed like it might be useful for what I'm playing around with, so I couldn't even make any kind of suggestion.

Are you familiar with the music21 project? It looks like a pretty decent set up for structuring music programmatically; unfortunately it's in python and I know next to nothing about python. It also seems to be quite focused on notation-related stuff, like slurs and ties and grace notes, etc., and I'm more interested in the structure-related stuff. But, it might be worth checking out to get some ideas on how they handle document structures and everything.

**Comment by mcory** [comment]
Completely forgot - that music21 project is at http://web.mit.edu/music21/.

**Comment by saebekassebil** [comment]
Not an issue for teoria, but an interesting problem nonetheless - closing here.
