### ISSUE TITLE
Add distribution file to repository

### ISSUE THREAD

**Issue by danigb** [saebekassebil/teoria#80]
I think it would be nice to have a pre-rendered dist/teoria.js ready for web environments inside the repository and in sync with the source.

**Comment by mjkaufer** [comment]
I second this

**Comment by saebekassebil** [comment]
I reckon I should just do this, as everybody seems to miss it. I'll have it done soon :)

**Comment by mjkaufer** [comment]
Thanks!

**Comment by saebekassebil** [comment]
Resolved per 2391e3f49c77f58fa4b0a6413facd5988a22c31f

I've built the bundle with

    $ browserify index.js --standalone teoria > teoria.js

Which basically just bundles it all up, and wraps it as a UMD module. Should be ready for use in most environments.
