### ISSUE TITLE
Expose the available scales

### ISSUE THREAD

**Issue by emanchado** [saebekassebil/teoria#94]
The file lib/scale.js contains a list of known scales that can be used in the constructor of the Scale class. The list isn't, however, available to code using requiring teoria, so if you wanted to, say, make a UI with a dropdown with scales, you would have to duplicate the list.

As it's trivial to expose the list, and it's useful, it would be nice if it was available. I can prepare the (trivial) patch if you want.

**Comment by saebekassebil** [comment]
Let's do that.

**Comment by saebekassebil** [comment]
Fixed in #95
